name: "create-child-issues"
description: "Creates child issues referencing back to original issue"
author: "rnystrom"
runs:
  using: "node12"
  main: "create-child-issues.js"
inputs:
  labels:
    description: A JSON array of label objects. Required keys "label" (string), "repos" (array of strings), with optional key "addLabels" (array of strings) to add labels to child issues.
    required: true
